name: Java CI with Maven
on:
  push:
    branches:
      - main
      - develop
      - feature/*
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '17', '22' ]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
            distribution: 'temurin'
            java-version: ${{ matrix.java }}

      - name: Build with Maven
        run: mvn -B clean install

      - name: Run tests
        run: mvn test

      - name: Run code analysis
        run: mvn checkstyle:check pmd:check spotbugs:check

      - name: Run SonarCloud analysis
        run: mvn sonar:sonar

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results-${{ matrix.java }}
          path: target/surefire-reports/

      - name: Upload code coverage
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage-${{ matrix.java }}
          path: target/site/jacoco/
