name: Java CI with Maven

on:
  push:
    branches:
      - main
      - develop
      - 'feature/*'
  pull_request:
    branches:
      - main
      - develop
      - 'feature/*'

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '17', '22' ]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}

      - name: Build with Maven
        run: mvn clean package

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/conference-citation-tool:${{ github.sha }} .

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker image
        run: |
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/conference-citation-tool:${{ github.sha }} ${{ secrets.DOCKERHUB_USERNAME }}/conference-citation-tool:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/conference-citation-tool:${{ github.sha }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/conference-citation-tool:latest

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          version: 'latest'
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          export_default_credentials: true

      - name: Authenticate to GKE
        run: |
          gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
          gcloud container clusters get-credentials ${{ secrets.GKE_CLUSTER_NAME }} --zone ${{ secrets.GKE_CLUSTER_ZONE }}

      - name: Deploy to GKE
        run: |
          kubectl set image deployment/conference-citation-tool-deployment conference-citation-tool=${{ secrets.DOCKERHUB_USERNAME }}/conference-citation-tool:${{ github.sha }}

